// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-articles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-articles.ts
var list_articles_default = defineTool({
  name: "list_articles",
  title: "Listar artigos",
  description: "Lista os artigos do usu\xE1rio autenticado, com filtro opcional por status ou categoria.",
  inputSchema: {
    status: z.enum(["draft", "scheduled", "published", "failed"]).optional().describe("Filtra pelo status do artigo."),
    category: z.string().trim().min(1).optional().describe("Filtra pela categoria."),
    limit: z.number().int().min(1).max(50).default(10).describe("M\xE1ximo de artigos retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("articles").select("id, title, status, category, slug, published_at, scheduled_at, created_at, featured_image_url").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-article.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_article_default = defineTool2({
  name: "get_article",
  title: "Ver artigo",
  description: "Retorna o conte\xFAdo completo e os dados de SEO de um artigo pelo ID.",
  inputSchema: {
    id: z2.string().uuid().describe("ID do artigo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("articles").select(
      "id, title, status, category, slug, content, excerpt, meta_title, meta_description, seo_keyword, focus_keyword, featured_image_url, published_at, scheduled_at, created_at, updated_at"
    ).eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Artigo n\xE3o encontrado" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { article: data }
    };
  }
});

// src/lib/mcp/tools/create-article-draft.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z3 } from "npm:zod@^3.25.76";
var create_article_draft_default = defineTool3({
  name: "create_article_draft",
  title: "Criar rascunho de artigo",
  description: "Cria um novo artigo em rascunho (status draft) para o usu\xE1rio autenticado, sem publicar.",
  inputSchema: {
    title: z3.string().trim().min(3).describe("T\xEDtulo do artigo."),
    category: z3.string().trim().min(1).describe("Categoria do artigo (ex.: esportes, politica)."),
    content: z3.string().trim().optional().describe("Conte\xFAdo em HTML ou texto."),
    excerpt: z3.string().trim().optional().describe("Resumo curto."),
    seo_keyword: z3.string().trim().optional().describe("Palavra-chave principal de SEO.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, category, content, excerpt, seo_keyword }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("articles").insert({
      user_id: ctx.getUserId(),
      title,
      category,
      content: content ?? null,
      excerpt: excerpt ?? null,
      seo_keyword: seo_keyword ?? null,
      status: "draft"
    }).select("id, title, status, category, created_at");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { article: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-blogs.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_blogs_default = defineTool4({
  name: "list_blogs",
  title: "Listar blogs",
  description: "Lista os blogs cadastrados pelo usu\xE1rio autenticado.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(20).describe("M\xE1ximo de blogs retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blogs").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { blogs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bvvhgwkjyfnjroudtbav";
var mcp_default = defineMcp({
  name: "postwp",
  title: "PostWP",
  version: "0.1.0",
  instructions: "Ferramentas do PostWP: liste e leia artigos, crie rascunhos e consulte blogs do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_articles_default, get_article_default, create_article_draft_default, list_blogs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
